### PR TITLE
Replace `code/` folder with git submodule

### LINKED ISSUE #17: Move contents of `code/` folder into "exercises" repo and replace with git submodule
As suggested by @dalonsoa, the `code/` subfolder could be a git submodule pointing to the exercises repo.

We might be able to get dependabot to autoupdate it for us, too.

### PR DESCRIPTION
**Pull request by alexdewar**
I have replaced the `code/` folder with a git submodule, pointing to the `unit_testing_Cpp_exercises` git repo. While we should manually bump the version of the code pointed to whenever we change it, I have also added a dependabot config file to auto-update it in case we forget.

Fixes #17.

### CODE REVIEW

**Review by dalonsoa — APPROVED** [review]
It looks good, however I'm not sure if there will be more things to change. In several points of the lessons, there are links to the code files. I guess those will need updating to point to the code repo?

**Comment by alexdewar** [comment]
Ah, yes they will need updating. My bad. I'll fix that up.

I expect that the code might change a bit but when it does we can just update the submodule too. I think the important thing is to have future changes to the code done in the code repository directly so we can keep it in sync, run the CI over it etc.

**Comment by alexdewar** [comment]
@dalonsoa Done and verified with `markdown-link-checker`.

This has made me wonder whether it might be useful to have `pre-commit` hooks and CI for our Carpentries courses...

**Comment by dalonsoa** [comment]
Great! And yes: probably it will be a good idea to add that type of checker.

**Review by lkr-ind — APPROVED** [review]
@alexdewar A small question. If someone wants to add a new code, is there a process by which these 2 repos (submodule in this one) would be synced automatically. 
or,
Do we need to do this manually?

**Comment by alexdewar** [comment]
@lkr-ind We should probably do it manually and submit a PR, maybe including any necessary corresponding changes to the course material. I did add a dependabot hook which will automatically open a PR if it sees that a newer version of the `code` submodule, but that was mostly just in case we forget to update it.

**Review by jamesturner246 — APPROVED** [review]
LGTM

**Pull request merged**
